# version: '3.8'

networks:
  transcendence:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  static_volume:

services:
  backend:
    container_name: backend_django
    build:
      context: ./services/backend/
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - transcendence
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./services/backend/Ft_transcendence:/app/
      - static_volume:/app/media/avatars
  postgres:
    container_name: postgres_db
    build:
      context: ./services/postgres/
      dockerfile: Dockerfile
    image: postgres
    restart: always
    networks:
      - transcendence
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - ./services/postgres/postgresql_data:/var/lib/postgresql/data

  redis:
    container_name: redis_cache
    build:
      context: ./services/redis/
      dockerfile: Dockerfile
    image: redis
    restart: always
    networks:
      - transcendence
    expose:
      - "6379"
    env_file:
      - .env

  nginx:
    container_name: nginx_serweb
    build:
      context: ./services/front/
      dockerfile: Dockerfile
    image: nginx
    restart: always
    networks:
      - transcendence
    depends_on:
      - backend
      - postgres
      - redis
    expose:
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/front/front:/var/www/html/
      - static_volume:/var/www/html/media/avatars

# docker rm -f $(docker ps -aq) && docker rmi $(docker images -q) &&  docker volume prune && docker compose down -v
