# Generated by Django 4.2.16 on 2024-12-10 16:55

from django.conf import settings
from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=180, unique=True)),
                ('gameroom_name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('game_spend_time', models.CharField(blank=True, max_length=10)),
                ('game_started', models.BooleanField(default=False)),
                ('game_ended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('players', models.ManyToManyField(blank=True, related_name='room_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
