FROM postgres:latest


# RUN apt-get update && apt-get install -y unzip

# COPY ./data.zip /tmp/

# RUN unzip /tmp/data.zip -d /var/lib/postgresql/data

# RUN chown -R postgres:postgres /var/lib/postgresql/data

EXPOSE 5432