# Generated by Django 4.2.16 on 2024-12-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
