# Generated by Django 4.2.16 on 2024-12-15 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managemanet', '0002_friendship_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='The user who initiated the block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_relationships', to=settings.AUTH_USER_MODEL),
        ),
    ]
