# Generated by Django 4.2.16 on 2024-11-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TicTacToe", "0002_remove_tictactoegame_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tictactoegame",
            name="board_state",
        ),
        migrations.RemoveField(
            model_name="tictactoegame",
            name="current_turn",
        ),
        migrations.RemoveField(
            model_name="tictactoegame",
            name="winner",
        ),
    ]
