# Generated by Django 4.2.16 on 2024-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TicTacToe", "0003_remove_tictactoegame_board_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tictactoegame",
            name="board_state",
            field=models.CharField(default="---------", max_length=9),
        ),
        migrations.AddField(
            model_name="tictactoegame",
            name="current_turn",
            field=models.CharField(
                choices=[("X", "Player X"), ("O", "Player O")],
                default="X",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="tictactoegame",
            name="winner",
            field=models.CharField(
                blank=True,
                choices=[("X", "Player X"), ("O", "Player O"), ("D", "Draw")],
                max_length=1,
                null=True,
            ),
        ),
    ]
