# Generated by Django 4.2.16 on 2024-12-06 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TicTacToe', '0006_tictactoegame_board_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoegame',
            name='player_o',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_o', to=settings.AUTH_USER_MODEL),
        ),
    ]
