# Generated by Django 4.2.16 on 2024-11-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicTacToeGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_state", models.CharField(default="---------", max_length=9)),
                (
                    "current_turn",
                    models.CharField(
                        choices=[("X", "Player X"), ("O", "Player O")],
                        default="X",
                        max_length=1,
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("X", "Player X"), ("O", "Player O"), ("D", "Draw")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_o",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_o",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_x",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_x",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
