# Generated by Django 4.2.16 on 2024-11-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TicTacToe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tictactoegame",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tictactoegame",
            name="updated_at",
        ),
    ]
