# Generated by Django 4.2.16 on 2024-11-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "TicTacToe",
            "0004_tictactoegame_board_state_tictactoegame_current_turn_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tictactoegame",
            name="board_state",
        ),
    ]
