"""
Django settings for transcendence project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-95(gwe)#h5n6=0bf40t-bi!)je$)v+ysim)+(u2w-p&%^us4(y"
DEBUG = True
EMAIL_PASSWORD =  "xayc rbdp axbd yfpk"
ALLOWED_HOSTS = ['*']  # Ajoute ton nom de domaine ou adresse IP ici si nécessaire

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'chat',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'user_managemanet',
    'a_game',
    'tournament',
    'TicTacToe',
    'ninja',
]

AUTH_USER_MODEL = 'user_managemanet.CustomUser'

MIDDLEWARE = [
     'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Gère les sessions
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Middleware d'authentification
    'django.contrib.messages.middleware.MessageMiddleware',  # Gère les messages
    'user_managemanet.middleware.DisableCSRF',
    'django.middleware.common.CommonMiddleware',
    'user_managemanet.middleware.JWTAuthenticationMiddleware', 

]


ROOT_URLCONF = 'transcendence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcendence.wsgi.application'



APPEND_SLASH = False



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "transcendence",
        'USER':"ymaaloum",
        'PASSWORD': "0000",
        'HOST' :'container_postgres',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CLIENT_ID_42=os.getenv('CLIENT_ID_42')
# CLIENT_SECRET_42=os.getenv('CLIENT_SECRET_42')
IP_ADRESS = os.getenv('IP_ADDRESS')
REDIRECT_URI_42= f"https://{IP_ADRESS}/api/callback/"

REDIRECT_URI_GOOGLE= "https://127.0.0.1/api/oauth/callback/"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/'media/'
CLIENT_ID_42="u-s4t2ud-48c20a1049615aa638dfa04140f65a2529efcc26099062bf5ca40d81afb5c191"
CLIENT_SECRET_42="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"
CLIENT_ID_GOOGLE="252248894810-0vvh65be1kr7r2428n5li0nhbgk5fjdc.apps.googleusercontent.com"
CLIENT_SECRET_GOOGLE="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"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Use in-memory channel layer
    },
}

CORS_ALLOW_HEADERS = [
    'content-type',
    'accept',
    'Authorization',
    'X-Requested-With',
]

REST_FRAMEWORK = {
    # 'DEFAULT_RENDERER_CLASSES': (
    #     'rest_framework.renderers.JSONRenderer',  # Use JSON instead of HTML
    # ),
}


CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

ASGI_APPLICATION = "transcendence.asgi.application"
WSGI_APPLICATION = 'transcendence.wsgi.application'